# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-e-2Bj19OPj3PZzMKeBRwFnwM5KJgpUr
"""

# app.py
import streamlit as st
import pandas as pd
from optimizer import load_data, run_ga

st.set_page_config(page_title="Mine Scheduler", layout="wide")
st.title("🪨 Mine Production & Haulage Optimizer")

uploaded_file = st.file_uploader("Upload your Surpac Block Model CSV", type=["csv"])

if uploaded_file:
    df = load_data(uploaded_file)
    st.subheader("📊 Block Model Preview")
    st.dataframe(df.head())

    if st.button("Run Optimization 🚀"):
        ga_instance = run_ga(df)
        solution, fitness, _ = ga_instance.best_solution()

        st.success("Optimization Complete!")
        st.write(f"✅ Best Fitness Value: {fitness:.2f}")

        selected_blocks = df[solution == 1]
        st.subheader("📦 Selected Blocks for Mining")
        st.dataframe(selected_blocks)

        st.metric("Total Ore (tonnes)", selected_blocks["OreTonnes"].sum())
        st.metric("Total Waste (tonnes)", selected_blocks["WasteTonnes"].sum())

